services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    environment:
      - PYTHONPATH=/
      - LOG_FORMAT=json
    ports:
      - "8000:8000"
    depends_on:
      - bot
    restart: unless-stopped
  bot:
    build:
      context: .
      dockerfile: packages/bot/Dockerfile
    volumes:
      - ./.env:/.env:ro
    environment:
      - PYTHONPATH=/
      - LOG_FORMAT=json
      - FAST_API=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped