services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    environment:
      - PYTHONPATH=/
    ports:
      - "8000:8000"
    restart: unless-stopped
  bot:
    build:
      context: .
      dockerfile: packages/bot/Dockerfile
    volumes:
      - ./.env:/.env:ro
    environment:
      - PYTHONPATH=/
      - FAST_API=http://backend:8000
    restart: unless-stopped